import sys
import os
import tkinter as Tk
from tkinter import *
window3=Tk()
window3.title("Revision")
window3.geometry("1000x800")

    
def back():
    python = sys.executable
    os.execl(python, python, * sys.argv)

TrianglesText=open("Resources\TrianglesAndTrigonometricRatios.txt","r")
SequencesText=open("Resources\SequencesRevision.txt","r")
AnglesText=open("Resources\AnglesRevision.txt","r")
IndicesText=open("Resources\IndicesRevision.txt","r")
PrimeText=open("Resources\PrimeNumbers.txt","r")

Triangles=TrianglesText.read()
Label2=Label(window3,text=Triangles,font=("none",10))

Angles=AnglesText.read()
Label3=Label(window3,text=Angles,font=("none",10))

Sequences=SequencesText.read()
Label4=Label(window3,text=Sequences,font=("none",10))

Indices=IndicesText.read()
Label5=Label(window3,text=Indices,font=("none",10))

Prime=PrimeText.read()
Label6=Label(window3,text=Prime,font=("none",10))




def ReadTriangles():
    def back2():
        Label2.pack_forget()
        Label1.pack()
        IndicesButton.pack()
        SequencesButton.pack()
        PrimesButton.pack()
        AnglesButton.pack()
        TrianglesButton.pack()
        BackButton.pack()
        BackButton2.destroy()
        window3.mainloop()
    Label2.pack()
    Label1.pack_forget()
    IndicesButton.pack_forget()
    SequencesButton.pack_forget()
    PrimesButton.pack_forget()
    AnglesButton.pack_forget()
    TrianglesButton.pack_forget()
    BackButton.pack_forget()
    BackButton2=Button(window3,text="Back",command=back2)
    BackButton2.pack()
    window3.mainloop()
def ReadAngles():
    def back3():
        Label3.pack_forget()
        Label1.pack()
        IndicesButton.pack()
        SequencesButton.pack()
        PrimesButton.pack()
        AnglesButton.pack()
        TrianglesButton.pack()
        BackButton.pack()
        BackButton2.destroy()
        window3.mainloop()
    Label3.pack()
    Label1.pack_forget()
    AnglesButton.pack_forget()
    TrianglesButton.pack_forget()
    IndicesButton.pack_forget()
    SequencesButton.pack_forget()
    PrimesButton.pack_forget()
    BackButton.pack_forget()
    BackButton2=Button(window3,text="Back",command=back3)
    BackButton2.pack()
    window3.mainloop()
def ReadIndices():
    def back4():
        Label5.pack_forget()
        Label1.pack()
        IndicesButton.pack()
        SequencesButton.pack()
        PrimesButton.pack()
        AnglesButton.pack()
        TrianglesButton.pack()
        BackButton.pack()
        BackButton2.destroy()
        window3.mainloop()
    Label5.pack()
    Label1.pack_forget()
    AnglesButton.pack_forget()
    TrianglesButton.pack_forget()
    IndicesButton.pack_forget()
    SequencesButton.pack_forget()
    PrimesButton.pack_forget()
    BackButton.pack_forget()
    BackButton2=Button(window3,text="Back",command=back4)
    BackButton2.pack()
    window3.mainloop()  
def ReadSequences():
    def back5():
        Label4.pack_forget()
        Label1.pack()
        IndicesButton.pack()
        SequencesButton.pack()
        PrimesButton.pack()
        AnglesButton.pack()
        TrianglesButton.pack()
        BackButton.pack()
        BackButton2.destroy()
        window3.mainloop()
    Label4.pack()
    Label1.pack_forget()
    AnglesButton.pack_forget()
    TrianglesButton.pack_forget()
    IndicesButton.pack_forget()
    SequencesButton.pack_forget()
    PrimesButton.pack_forget()
    BackButton.pack_forget()
    BackButton2=Button(window3,text="Back",command=back5)
    BackButton2.pack()
    window3.mainloop() 
    
def ReadPrime():
    def back6():
        Label6.pack_forget()
        Label1.pack()
        IndicesButton.pack()
        SequencesButton.pack()
        PrimesButton.pack()
        AnglesButton.pack()
        TrianglesButton.pack()
        BackButton.pack()
        BackButton2.destroy()
        window3.mainloop()
    Label6.pack()
    Label1.pack_forget()
    AnglesButton.pack_forget()
    TrianglesButton.pack_forget()
    IndicesButton.pack_forget()
    SequencesButton.pack_forget()
    PrimesButton.pack_forget()
    BackButton.pack_forget()
    BackButton2=Button(window3,text="Back",command=back6)
    BackButton2.pack()
    window3.mainloop() 
    
     
Label1=Label(window3,text="Which mathematics subject do you want?")
AnglesButton=Button(window3,text="Angles",command=ReadAngles)
TrianglesButton=Button(window3,text="Triangles and trigonometrical ratios",command=ReadTriangles)
IndicesButton=Button(window3,text="Indices",command=ReadIndices)
SequencesButton=Button(window3,text="Sequences",command=ReadSequences)
PrimesButton=Button(window3,text="Prime Numbers",command=ReadPrime)
BackButton=Button(window3,text="Back",command=back)
Label1.pack()
IndicesButton.pack()
SequencesButton.pack()
PrimesButton.pack()
AnglesButton.pack()
TrianglesButton.pack()
BackButton.pack()
window3.mainloop()

